spring:
  application:
    name: interlinkhub
  config:
    import: optional:file:.env[.properties]
  security:
    jwt:
      secret: ${JWT_SECRET}
      expiration-minutes: 240
  datasource:
    url: jdbc:mysql://localhost:3306/interlinkhub?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

server:
  port: 8080